CREATE TABLE star_metadata (
    star_id VARCHAR2(50) PRIMARY KEY,  -- Unique ID of the star (e.g., TIC ID)
    name VARCHAR2(100),               -- Name of the star
    brightness NUMBER(10, 4),         -- Brightness magnitude of the star
    observation_time TIMESTAMP,       -- Observation time
    catalog VARCHAR2(50)              -- Catalog source (e.g., TESS, Kepler)
);

-- Index for faster lookup on catalog and brightness range
CREATE INDEX idx_star_catalog_brightness ON star_metadata (catalog, brightness);

CREATE TABLE file_paths (
    file_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing file ID
    star_id VARCHAR2(50) REFERENCES star_metadata (star_id),     -- Foreign key linking to star_metadata
    file_type VARCHAR2(50),                                     -- Type of file (e.g., raw, processed, visualization)
    file_name VARCHAR2(200),                                    -- Name of the file
    minio_path VARCHAR2(500),                                   -- Path to the file in MinIO
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP               -- Time of file creation/upload
);

-- Index for faster retrieval by file type
CREATE INDEX idx_file_type ON file_paths (file_type);

-- Index for combining star_id and file_type for specific queries
CREATE INDEX idx_star_file_type ON file_paths (star_id, file_type);

CREATE TABLE analysis_results (
    result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing result ID
    star_id VARCHAR2(50) REFERENCES star_metadata (star_id),      -- Foreign key linking to star_metadata
    period NUMBER(10, 4),                                         -- Orbital period detected
    duration NUMBER(10, 4),                                       -- Duration of the transit
    depth NUMBER(10, 4),                                          -- Depth of the transit dip
    power NUMBER(10, 4),                                          -- Signal power of the detection
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP                 -- Time of result generation
);

-- Index for faster lookups by star_id
CREATE INDEX idx_analysis_star_id ON analysis_results (star_id);

-- Index for querying analysis results based on specific metrics
CREATE INDEX idx_analysis_period_depth ON analysis_results (period, depth);

ALTER TABLE file_paths
ADD CONSTRAINT fk_file_star FOREIGN KEY (star_id) REFERENCES star_metadata (star_id);

SELECT constraint_name, constraint_type
FROM user_constraints
WHERE table_name = 'FILE_PATHS';

ALTER TABLE file_paths
DROP CONSTRAINT fk_file_star;

ALTER TABLE file_paths
ADD CONSTRAINT fk_file_star FOREIGN KEY (star_id) REFERENCES star_metadata (star_id);


SELECT a.constraint_name, a.constraint_type, b.column_name, c.r_constraint_name
FROM user_constraints a
JOIN user_cons_columns b
ON a.constraint_name = b.constraint_name
LEFT JOIN user_constraints c
ON a.r_constraint_name = c.constraint_name
WHERE a.table_name = 'FILE_PATHS'
AND a.constraint_type = 'R';

